### ISSUE TITLE
No audio in SRT Live Streem

### ISSUE THREAD

**Issue by Venkateshmadipalli** [shogo4405/HaishinKit.swift#1540] opened 2024-08-20 13:03 UTC
### Describe the bug

I am using the HaishinKit.Swift library to create an SRT stream, and the video stream is working perfectly on the server side. However, I’ve encountered an issue where the audio track is not being passed through. Despite successfully establishing the stream, no audio is received on the server.

Could you please provide guidance or suggest a solution to ensure that the audio is included in the stream?

Thank you for your support!      
this my sample code

```swift                  
 private var connection: SRTConnection!
    private var stream: SRTStream!
@IBOutlet weak var preView: MTHKView!
 override func viewDidLoad() {
        super.viewDidLoad()
 connection = .init()
        stream = SRTStream(connection: connection)
 stream.videoOrientation = .landscapeRight
        stream.sessionPreset = .hd1280x720
        stream.videoSettings.videoSize = .init(width: 1920, height: 1080)
       // stream.videoSettings.bitRate = 2000000
        stream.videoSettings.maxKeyFrameIntervalDuration = 2
        stream.videoSettings.profileLevel = kVTProfileLevel_HEVC_Main_AutoLevel as String
        stream.frameRate = 25
        stream.isMultiTrackAudioMixingEnabled = false
        stream.audioMixerSettings = IOAudioMixerSettings(
            sampleRate: 44100,
            channels: 0
        )
        stream.audioMixerSettings.isMuted = false
        stream.audioMixerSettings.mainTrack = 0
        stream.audioSettings.bitRate = 64 * 1000
        stream.audioSettings.downmix = true
         stream.audioSettings.channelMap  = nil
        stream.audioMixerSettings.tracks [.init()]?.isMuted = false
        stream.audioMixerSettings.tracks [.init()]?.downmix = true
        stream.audioMixerSettings.tracks [.init()]?.channelMap = nil
        stream.videoMixerSettings.mode = .passthrough
        stream.videoMixerSettings.isMuted = false
}
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
 let audios = AVCaptureDevice.default(for: .audio)
stream.attachAudio(audios,track: 0){audio,error in 
        }
       let camera = AVCaptureDevice.default(.builtInWideAngleCamera, for: .video, position: .back)
        if #available(iOS 13.0, *) {
            stream.attachCamera(camera) { error,_  in
                // print(error)
            }
}
  @IBAction func stateLiveAction(publish: UIButton) {
        Task { @MainActor in
            if publish.isSelected {
                UIApplication.shared.isIdleTimerDisabled = false
                stream.close()
                await connection.close()
                publish.setTitle("●", for: [])
            } else {
                
                    UIApplication.shared.isIdleTimerDisabled = true
                try await self.connection.open(URL(string: Preference.default.uri!))
                    self.stream.publish("")
                    print("Preference.default.uri!",Preference.default.uri!)
                   
                    
                    publish.setTitle("■", for: [])
               
            }
            publish.isSelected.toggle()
        }
    }
```

### To Reproduce

1. Setting up Audio configuration in AppDelage
2. Initializing the streamer.
3. Attaching the audio and video devices to streamer.
4. Building the SRT url and passing it to streamer and staring the live stream.

### Expected behavior

 we are expecting Audio should be played in the server side 

### Version

1.9.2

### Smartphone info.

XR

**Comment by shogo4405** [comment] 2024-08-20 14:25
It works for me. 1.9.2. It works on my end. Does the same issue occur with the Demo project in version 1.9.x? https://github.com/shogo4405/HaishinKit.swift/tree/release/1.9.x/Examples
```
Input #0, mpegts, from 'srt://0.0.0.0:9998?mode=listener':B 
  Duration: N/A, start: 0.100000, bitrate: N/A
  Program 1 
  Stream #0:0[0x100]: Video: h264 (Baseline) ([27][0][0][0] / 0x001B), yuv420p(progressive), 854x480, 60 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: aac (LC), 44100 Hz, mono, fltp, 65 kb/s
```

**Comment by Venkateshmadipalli** [comment] 2024-08-21 10:22
i used 1.9.2 version and 2.0.0 version also still i am facing the same issue (no audio in srt live )  
this my sample srt url srt://000.46.002.1001:00000?mode=caller&passphrase=179990000057&streamid=000000000000000
2024-21-08 15:44:53.610 [Info] [com.haishinkit.SRTHaishinKit] [SRTSocket.swift:55] status > SRT Socket Connected


and in console  i am getting this audio response  

2024-21-08 15:27:38.903 [Info] [com.haishinkit.Exsample.iOS] [IngestViewController.swift:84] viewWillAppear(_:) > viewWillAppear
2024-21-08 15:27:38.965 [Info] [com.haishinkit.Exsample.iOS] [IngestViewController.swift:298] didRouteChangeNotification(_:) > name = AVAudioSessionRouteChangeNotification, object = Optional(<AVAudioSession: 0x3021fc880>), userInfo = Optional([AnyHashable("AVAudioSessionRouteChangePreviousRouteKey"): <AVAudioSessionRouteDescription: 0x3021f1110, 
inputs = (
); 
outputs = (
    "<AVAudioSessionPortDescription: 0x3021f1140, type = Speaker; name = Speaker; UID = Speaker; selectedDataSource = (null)>"
)>, AnyHashable("AVAudioSessionRouteChangeReasonKey"): 3])
2024-21-08 15:27:39.027 [Warn] [com.haishinkit.HaishinKit] [VideoDeviceUnit.swift:44] output > device doesn't support this color format 32.
2024-21-08 15:27:40.096 [Info] [com.haishinkit.Exsample.iOS] [IngestViewController.swift:298] didRouteChangeNotification(_:) > name = AVAudioSessionRouteChangeNotification, object = Optional(<AVAudioSession: 0x3021fc880>), userInfo = Optional([AnyHashable("AVAudioSessionRouteChangePreviousRouteKey"): <AVAudioSessionRouteDescription: 0x3021feb80, 
inputs = (
    "<AVAudioSessionPortDescription: 0x3021febb0, type = MicrophoneBuiltIn; name = iPhone Microphone; UID = Built-In Microphone; selectedDataSource = Bottom>"
); 
outputs = (
    "<AVAudioSessionPortDescription: 0x3021fec30, type = Speaker; name = Speaker; UID = Speaker; selectedDataSource = (null)>"
)>, AnyHashable("AVAudioSessionRouteChangeReasonKey"): 3])
2024-21-08 15:27:40.159 [Info] [com.haishinkit.Exsample.iOS] [IngestViewController.swift:298] didRouteChangeNotification(_:) > name = AVAudioSessionRouteChangeNotification, object = Optional(<AVAudioSession: 0x3021fea90>), userInfo = Optional([AnyHashable("AVAudioSessionRouteChangeReasonKey"): 3, AnyHashable("AVAudioSessionRouteChangePreviousRouteKey"): <AVAudioSessionRouteDescription: 0x3021f0c10, 
inputs = (
    "<AVAudioSessionPortDescription: 0x3021f0d40, type = MicrophoneBuiltIn; name = iPhone Microphone; UID = Built-In Microphone; selectedDataSource = Bottom>"
); 
outputs = (
    "<AVAudioSessionPortDescription: 0x3021f3800, type = Speaker; name = Speaker; UID = Speaker; selectedDataSource = (null)>"
)>])
2024-21-08 15:27:42.643 [Info] [com.haishinkit.Exsample.iOS] [IngestViewController.swift:298] didRouteChangeNotification(_:) > name = AVAudioSessionRouteChangeNotification, object = Optional(<AVAudioSession: 0x3021fea90>), userInfo = Optional([AnyHashable("AVAudioSessionRouteChangePreviousRouteKey"): <AVAudioSessionRouteDescription: 0x3021e05c0, 
inputs = (
    "<AVAudioSessionPortDescription: 0x3021e05d0, type = MicrophoneBuiltIn; name = iPhone Microphone; UID = Built-In Microphone; selectedDataSource = (null)>"
); 
outputs = (
    "<AVAudioSessionPortDescription: 0x3021e0670, type = Speaker; name = Speaker; UID = Speaker; selectedDataSource = (null)>"
)>, AnyHashable("AVAudioSessionRouteChangeReasonKey"): 3])
2024-21-08 15:27:42.660 [Info] [com.haishinkit.Exsample.iOS] [IngestViewController.swift:298] didRouteChangeNotification(_:) > name = AVAudioSessionRouteChangeNotification, object = Optional(<AVAudioSession: 0x3021fc880>), userInfo = Optional([AnyHashable("AVAudioSessionRouteChangeReasonKey"): 3, AnyHashable("AVAudioSessionRouteChangePreviousRouteKey"): <AVAudioSessionRouteDescription: 0x3021e42d0, 
inputs = (
    "<AVAudioSessionPortDescription: 0x3021e4120, type = MicrophoneBuiltIn; name = iPhone Microphone; UID = Built-In Microphone; selectedDataSource = (null)>"
); 
outputs = (
    "<AVAudioSessionPortDescription: 0x3021e4090, type = Speaker; name = Speaker; UID = Speaker; selectedDataSource = (null)>"
)>])
2024-21-08 15:27:42.672 [Info] [com.haishinkit.HaishinKit] [AudioMixerTrack.swift:166] setUp(_:) > inputFormat:<AVAudioFormat 0x3000d8cd0:  1 ch,  44100 Hz, Int16>, outputFormat:<AVAudioFormat 0x3000d8f50:  1 ch,  44100 Hz, Int16>
2024-21-08 15:27:42.686 [Warn] [com.haishinkit.HaishinKit] [VideoDeviceUnit.swift:44] output > device doesn't support this color format 32.
2024-21-08 15:27:43.930 [Info] [com.haishinkit.HaishinKit] [AudioCodec.swift:140] makeAudioConverter() > inputFormat:<AVAudioFormat 0x3000d8f50:  1 ch,  44100 Hz, Int16>,outputFormat:<AVAudioFormat 0x3000ce620:  1 ch,  44100 Hz, aac  (0x00000002) 0 bits/channel, 0 bytes/packet, 1024 frames/packet, 0 bytes/frame>


Could you please provide guidance or suggest a solution to ensure that the audio is included in the stream?

Thank You

**Comment by shogo4405** [comment] 2024-08-21 11:49
Unfortunately, I don't understand it. I think it might be better to give up and look for another software. Since no further progress can be expected, I'll close this issue.

**Closed by shogo4405** 2024-08-21 11:49 UTC
Labels: SRTHaishinKit

**Comment by jhays** [comment] 2024-09-13 18:24
Hello, 
I understand this issue has been closed, but I suspect I may have just run into the same issue and wanted to report it as well. 

I tested broadcasting in an app via SRTHaishinKit up to our video service provider, Mux. I'm also finding that there is no audio track present. 

I then ran the HaishinKit iOS example, set the URL to an SRT url that points to our Mux service, where I am able to see live stream stats on the Mux dashboard. Even when streaming with SRT from the HaishinKit 1.9.3 iOS example code, no audio is present. From the Mux dashboard, it appears that no audio track is arriving at the server at all.

The screenshots below are from my Mux dashboard. If an audio track is present, it should appear in the tracks list. But in this case, there is no audio track arriving at the server (SRT Listener side), just a single video track @ 480. 

As a side note, I'm also noticing that the resolution appears to locked at 854x480. I didn't try changing this in the HaishinKit example project, but when I attempt to broadcast via SRT from my own app with SRTHaishinKit, even if I alter the SRTStream's videoSettings to change the resolution, the changes do not appear to be working. The listener side seems to always receive 854x480.

Based on this testing, and confirming that I can also reproduce the no audio issue when running the HaishinKit example project, it seems there may be an issue with SRTHaishinKit.

If there is any further info I can provide that would be helpful with debugging the issue, please let me know and I will do my best to provide it. 

Thank you!

![Screenshot 2024-09-13 at 1 18 23 PM](https://github.com/user-attachments/assets/fd7312d9-d5db-48fb-ab3c-3c1706fe4150)
![Screenshot 2024-09-13 at 1 18 51 PM](https://github.com/user-attachments/assets/e06d7ca8-955e-4534-ade7-118dfb92896a)

**Comment by shogo4405** [comment] 2024-09-20 15:09
This commit might improve the issue. However, I can't say for certain as I don't have the environment to reproduce it. 2c7c328b

**Comment by jhays** [comment] 2024-09-23 20:35
I tested with the suggested commit and it appears to have been successful. From your `feature/optimize-mthkview` branch (I grabbed this because it included the fix you mentioned) I was able to stream using SRT and the HEVC video codec, and audio also worked successfully. I tested viewing the live video from the Mux dashboard and the audio track was present.

Thank you!
