### ISSUE TITLE
When using RTMP to stream to Facebook, it is missing an audio track

### ISSUE THREAD

**Issue by createmedia2017** [shogo4405/HaishinKit.swift#778] opened 2020-11-05 14:18 UTC
**Describe the bug**
When using Haishinkit 1.1.0 with ios14.1, it sometimes fails to stream to Facebook normally. The probability of occurrence is about 60%.

**To Reproduce**
1. Go to Facebook web
2. Click on 'Live Video'
3. Click on 'Use Stream Key'
4. Copy Server URL and Stream Key to Haishinkit
5. Go live and See error

**Expected behavior**
Stream to Facebook normally.

**Screenshots**
![1604584053680](https://user-images.githubusercontent.com/70458354/98252285-b1a6b900-1fb4-11eb-8c80-ff50243bb927.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone SE / iPhone 7 / iPhone 8p / iPhone XR / iPad Pro 11.9
 - OS: iOS14.1
 - Version Haishinkit 1.1.0

**Additional context**
Use Haishinkit 0.9.1 with ios13 and below to stream to Facebook normally.

**Comment by createmedia2017** [comment] 2020-11-07 01:02
Just made a donation using PayPal.
Hope to help resolve this issue.
Everyone supports shogo4405.

**Comment by shogo4405** [comment] 2021-01-10 14:22
I can't reproduce it. I will close this issue.

**Closed by shogo4405** 2021-01-10 14:22 UTC
