### ISSUE TITLE
SRT Connection is not streaming audio to server 

### ISSUE THREAD

**Issue by sudar0** [shogo4405/HaishinKit.swift#1546] opened 2024-08-26 13:05 UTC
### Describe the bug

Can please resolve this issue 
i have tried SRTHaishinkit. swift 0.1.2 and Haishinkit. swift 1.9.3 
in  SRTHaishinkit. swift 0.1.2 i can hear  audio in live video server 
but Haishinkit. swift 1.9.3  i cannot hear  audio in live video server  and latest version of Haishinkit. swift also but i am facing same problem (i used example code only)

### To Reproduce

i am clone  the example code from git hub 
and given my srt url  " srt://123.46.222.1001:11110?mode=caller&passphrase=111117"(example url)
start the live but no audio in live 

### Expected behavior

we should be able to hear audio in live video

### Version

1.9.3

### Smartphone info.

10R,IPHONE 8

**Comment by shogo4405** [comment] 2024-08-26 16:02
Unfortunately, I can't reproduce the issue on my end, so resolving it is difficult.

**Comment by shogo4405** [comment] 2024-08-26 16:03
Dupilicate as https://github.com/shogo4405/HaishinKit.swift/issues/1540

**Comment by sudar0** [comment] 2024-08-27 07:39
Thank you for the responding 
When i run your sample project (example ios ) i am  getting this response 
Is this  the reason why i am not getting audio in liveVideo?

AVAudioSessionRouteChangeNotification, object = Optional(<AVAudioSession: 0x3009bedd0>), userInfo = Optional([AnyHashable("AVAudioSessionRouteChangePreviousRouteKey"): <AVAudioSessionRouteDescription: 0x3009b3340, 
inputs = (
    "<AVAudioSessionPortDescription: 0x3009b3370, type = MicrophoneBuiltIn; name = iPhone Microphone; UID = Built-In Microphone; selectedDataSource = (null)>"
); 
outputs = (
    "<AVAudioSessionPortDescription: 0x3009b33f0, type = Speaker; name = Speaker; UID = Speaker; selectedDataSource = (null)>"
)>

**Comment by shogo4405** [comment] 2024-08-27 11:22
No.

At a minimum, you need to provide details about the environment you’re using, such as the server name. If the issue is with viewing, you must include the name of the software you’re using; otherwise, I can’t provide support. While it’s your choice to shorten the template, I won’t be able to assist you.

**Comment by sudar0** [comment] 2024-08-27 12:43
Thank you for you response 
We use Nimble Streamer to receive the SRT stream and Player is Softvelum SLDP player 

1. first i will run your sample code 
2. Then i will call api and  i will get response like ipaddress ,port and passphrase 
3. Then i will pass this values to uri like srt://123.46.222.1001:11110?mode=caller&passphrase=111117"  and now i will connect 
4.  in server side i am able to see the video but  not able to hear the audio 
please let me now any other information require.

**Comment by shogo4405** [comment] 2024-08-27 12:49
If you're using a commercial server, I’d recommend asking their support team.

**Closed by shogo4405** 2024-08-27 12:49 UTC
Labels: SRTHaishinKit

**Comment by sudar0** [comment] 2024-08-28 04:49
But it's working prefect  when i am using  SRTHaishinkit. swift 0.1.2 what was the difference?

**Comment by shogo4405** [comment] 2024-08-28 10:41
Please investigate and let me know! Thank you.
