### ISSUE TITLE
AttachStream to multiple instance of GLHKView 

### ISSUE THREAD

**Issue by Goule** [shogo4405/HaishinKit.swift#534] opened 2019-05-06 15:01 UTC
Hello,

I'm trying to attach a stream's preview to 2 différents GLHKView, but I can't find how to do it.
It is possible ? 

Use case : the root screen which contains the mini preview, and a second detail screen with a full screen preview (displayed on tap on the first mini preview).

Thanks for your work

**Comment by floriangbh** [comment] 2019-05-13 15:00
I have the same issue here. Seems to be a duplicate of https://github.com/shogo4405/HaishinKit.swift/issues/503

**Closed** 2019-05-16 09:48 UTC
