### ISSUE TITLE
1080p capture stutters on iPhone 12 Pro/Max

### ISSUE THREAD

**Issue by CubitSpeed** [shogo4405/HaishinKit.swift#818] opened 2021-02-01 02:28 UTC
**Describe the bug**
The 1080p capture stutters on the iPhone 12 Pro/Max.
Stuttering affects preview, local recording, and stream.

**To Reproduce**
1. Clone iOS Example
2. Change `rtmpStream.captureSettings.sessionPreset` to be `AVCaptureSession.Preset.hd1920x1080`
3. Run project on iPhone
4. Switch back/front camera until issue occurs.

**Expected behavior**
Preview, local recording, and stream should be smooth. No stuttering

**Screenshots**
Please see attached video with reproduction steps and the stutter:
https://user-images.githubusercontent.com/67028273/106406758-23917180-63ef-11eb-936e-a7dfb66c179e.MP4

**Smartphone**
 - Device: iPhone 12 Pro and iPhone 12 Pro Max
 - OS: iOS14 (newest)
 - Version: HaishinKit.swift Master

**Additional context**
Does not happen on iPhone 12 (non Pro/Max). Or any other iPhone devices I have tried.

Very strange: sometimes zooming in will solve the issue. But will re-occur after zoom out.

**Comment by themaxsmith** [comment] 2021-02-06 20:20
I have seen this issue on an iPhone 12 as well using RTMP. Happens on the High / Main profile. The baseline profile seems to be unaffected. If I use SRTHashinkit it is also unaffected even if on High / Main profile

**Comment by shogo4405** [comment] 2023-02-02 13:36
Would you like to reproduce now? That may have been the cause `AVCaptureDecice#activeFormat`.
If it doesn't reproduce, I will close it. Thank you.

**Comment by shogo4405** [comment] 2023-02-07 14:06
Currently iOS16. It is hard to reproduce. I will close.

**Closed by shogo4405** 2023-02-07 14:06 UTC
Labels: bug
