### ISSUE TITLE
HLSService doesn't works on SwiftUI.

### ISSUE THREAD

**Issue by buzai** [shogo4405/HaishinKit.swift#1267] opened 2023-08-19 13:42 UTC
### Describe the bug

the http://192.168.1.12:8080/hello/playlist.m3u8 can`t be open
some error log is 
```
 NSUnderlyingError=0x281072760 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
  [Warn] [com.haishinkit.HaishinKit] [TSWriter.swift:364] rotateFileHandle(_:) > Error Domain=NSCocoaErrorDomain Code=4 "“931432.ts” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
```

### To Reproduce

ios code  

```
import SwiftUI
import HaishinKit
import AVFoundation
import VideoToolbox


struct MTHKSwiftUiView: UIViewRepresentable {
    var videoHttp: VideoHttp

    var mthkView = MTHKView(frame: .zero)

    func makeUIView(context: Context) -> MTHKView {
        mthkView.videoGravity = .resizeAspectFill
        mthkView.attachStream(videoHttp.stream)
        return mthkView
    }

    func updateUIView(_ uiView: MTHKView, context: Context) {
        mthkView.attachStream(videoHttp.stream)
    }
}

class VideoHttp: ObservableObject {
    var stream: HTTPStream = HTTPStream()
    var httpService = HLSService(domain: "", type: "_http._tcp", name: "HaishinKit", port: 8080)

    init() {
        stream.attachCamera(AVCaptureDevice.default(.builtInWideAngleCamera, for: .video, position: .back))
        stream.attachAudio(AVCaptureDevice.default(for: .audio))
        stream.publish("hello")
    }

    func start() {
        httpService.addHTTPStream(stream)
        httpService.startRunning()
    }
}


struct ContentView: View {
    @StateObject var videoHttp = VideoHttp()

    var body: some View {
        VStack {
            MTHKSwiftUiView(videoHttp: videoHttp)
                .frame(width: 300, height: 300, alignment: .center)
                .onAppear(perform: {
                    videoHttp.start()
                })
        }
        .padding()
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

```

### Expected behavior

open hls in chrome

### Version

latest

### Smartphone info.

ios 16.4

**Comment by buzai** [comment] 2023-08-19 13:45
MTHKSwiftUiView can see the preview video, but the browser cannot open that address

**Comment by shogo4405** [comment] 2023-08-20 01:39
I have confirmed the functionality on macOS with the UIKit version. Indeed, the code you provided doesn't work. I haven't tested it in SwiftUI yet.

**Comment by buzai** [comment] 2023-08-23 13:03
@shogo4405 I tried a similar code on macOS, it works, but not on ios

**Comment by kafejo** [comment] 2023-08-24 06:52
I tried UIKit version on iOS and same problem (Xcode 15 beta 5, iOS 17 beta).

**Comment by shogo4405** [comment] 2023-10-09 13:13
Due to a lack of available maintenance time, I have decided to remove the HLSService feature. This ticket will be marked as invalid and closed. Thank you for your understanding.

**Closed by shogo4405** 2023-10-09 13:13 UTC
Labels: invalid
