### ISSUE TITLE
audioCodec delegate crash

### ISSUE THREAD

**Issue by mkrn** [shogo4405/HaishinKit.swift#1233] opened 2023-07-12 21:14 UTC
### Describe the bug

All of a sudden crash on 
delegate?.audioCodec(self, didOutput: buffer, presentationTimeStamp: ringBuffer.presentationTimeStamp)

### To Reproduce

Not sure. Here's the recording of the stack:

https://github.com/shogo4405/HaishinKit.swift/assets/1870075/84871b91-ce54-4c08-8d25-bb3d3d259a77

### Expected behavior

Shouldn't crash

### Version

1.5.2

### Smartphone info.

iPhone 13 pro

**Comment by shogo4405** [comment] 2023-07-19 11:26
Is the issue still occurring? This kind of problem can sometimes happen due to excessive recursive processing or Xcode bugs. It might have improved since I stopped the recursive processing. https://github.com/shogo4405/HaishinKit.swift/pull/1236.

**Comment by mkrn** [comment] 2023-07-28 13:13
You're right, it's not in production.

**Comment by shogo4405** [comment] 2023-07-29 08:21
I believe that the issues have been resolved in #1236 and #1255. If I can reproduce the problem locally, I will reopen the ticket. As it doesn't seem to occur in the production environment, I will close it for now.

**Closed by shogo4405** 2023-07-29 08:21 UTC
