### ISSUE TITLE
There is no sound while broadcasting from the recording screen.

### ISSUE THREAD

**Issue by AntonShapoval** [shogo4405/HaishinKit.swift#647] opened 2020-03-03 09:56 UTC
There is no sound while broadcasting from the recording screen.

1. Run screen recording with microphone in off state
2. Switch microphone to on state
3. Check the presence of sound. It is mute.

**Comment by shogo4405** [comment] 2020-03-07 06:08
I can't reproduced. In this case, have a problem playback side.

**Comment by AntonShapoval** [comment] 2020-03-07 10:03
I worked with AWS Elemental MediaLive and Live Streams from Wowza.

**Comment by shogo4405** [comment] 2020-03-07 10:20
Please addtional this information. Playback side.

``` 
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
   - e.g. iOS AVAudioPlayer with HLS
   - e.g Android ExoPlayer with RTMP ? HLS?
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
```

**Comment by AntonShapoval** [comment] 2020-03-07 12:42
I sent video stream from (by screen recording): 
- iPhone 6S (iOS 13.1.3)
- iPhone X (iOS 13.3.1)

Watching the video was on:
- Firefox 73.0.1
- macOS Catalina 10.15

**Comment by AntonShapoval** [comment] 2020-03-07 12:55
Also tried an experiment:
I started a screen recording session with the microphone turned off. But at this time I was sending CMSampleBuffers with audio from a file. Next, when the microphone was turned on, the audio signal was sent from the microphone instead of the stream from the file. On the receiver side (AWS), the sound in this case was constant, but in a distorted form (since I was doing something it seems not quite right).

**Comment by leo150** [comment] 2020-07-16 16:52
This framework doesn't have audio mixer. Frames of `audioApp` and `audioMic` type having diff sample rate most of the time. You need to implement a mixer and provide frames to HK after mixing.

**Comment by shogo4405** [comment] 2020-07-28 13:40
well. I can't reproduce. I will close this Issue.

**Closed by shogo4405** 2020-07-28 13:40 UTC
