### ISSUE TITLE
iOS 14 Black Screen Issue

### ISSUE THREAD

**Issue by kumaresan-cgvak** [shogo4405/HaishinKit.swift#772] opened 2020-10-29 16:36 UTC
**Describe the bug**
We are getting a black screen in iOS 14 while trying to stream live video using RTMP with MUX.

**To Reproduce**
1. Start a stream using MTHKView via RTMP. 
2. Randomly getting Black Screen while we start the stream in iOS 14.

**Expected behavior**
App Should stream video without black screen.

**Screenshots**
<img width="473" alt="Screenshot 2020-10-29 at 10 04 08 PM" src="https://user-images.githubusercontent.com/5547152/97603797-cc1be800-1a32-11eb-8d0c-75253ffb18cb.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus, iPhone X, etc
 - OS: iOS 14.1

**Comment by ArchieGoodwin** [comment] 2020-11-03 13:47
Have the same issue. When fresh install app. Second time it is working. When issue happens getting this in log: fopen failed for data file: errno = 2 (No such file or directory)

**Comment by ArungokulPersonal** [comment] 2020-11-04 13:59
@ArchieGoodwin Kindly use the below code in the view controller in which you are live streaming with haishinkit.

/*******CODE***********/
let session = AVAudioSession.sharedInstance()
        do {
            // https://stackoverflow.com/questions/51010390/avaudiosession-setcategory-swift-4-2-ios-12-play-sound-on-silent
            if #available(iOS 10.0, *) {
                try session.setCategory(.playAndRecord, mode: .default, options: [.defaultToSpeaker, .allowBluetooth])
            } else {
                session.perform(NSSelectorFromString("setCategory:withOptions:error:"), with: AVAudioSession.Category.playAndRecord, with: [
                    AVAudioSession.CategoryOptions.allowBluetooth,
                    AVAudioSession.CategoryOptions.defaultToSpeaker
                ])
                try session.setMode(.default)
            }
            try session.setActive(true)
        } catch {
            logger.error(error)
        }
/*******CODE***********/

This is used in the app delegate didfinishlaunchingwithoptions method. In the example they've provided the app has to be killed and reused every time so only they've used this piece of code in the didfinishlaunchingwithoptions method and henceforth it's working correctly.

**Comment by ArchieGoodwin** [comment] 2020-11-04 14:04
I am using this code in view controller where I have streaming setup. The problem is that sometimes all working fine, sometimes no for some users no.

**Comment by rursache** [comment] 2020-11-06 16:25
this also happens randomly on some iOS 13 users, setting AVAudioSession's category as @ArungokulPersonal mentioned won't help as that's a requirement anyway to actually get a video/audio feed in the first place

**Comment by GeneticGenesis** [comment] 2020-11-30 14:19
Hey @kumaresan-cgvak 

I had this same issue, it triggered for me after upgrading to iOS 14.2 from 14.1, I believe it to be a corruption in the XCode cache. 

Here's how I fixed it:

```
cd ~/Library/Developer/Xcode/iOS\ DeviceSupport
rm -rf 14.2\ \(18B92\)
```
(Or whatever build you have cached)

From then on my launches have been normal again.

Let me know if this helps.

**Comment by shogo4405** [comment] 2020-12-02 11:37
I see this issue is resolved. I will close this issue. Thank u.

**Closed by shogo4405** 2020-12-02 11:37 UTC

**Comment by ArchieGoodwin** [comment] 2020-12-02 12:53
It is not fixed. Fix from @GeneticGenesis did not fix this.

**Comment by zeroAps** [comment] 2021-09-02 10:35
This seems still to be an active issue.

**Comment by ManueGE** [comment] 2022-03-09 19:05
We have been able to fix this if we modify `attachStream` in `HKView`. 

Currently we have this: 

```
    open func attachStream(_ stream: NetStream?) {
        guard let stream: NetStream = stream else {
            layer.session?.stopRunning()
            layer.session = nil
            currentStream = nil
            return
        }

        stream.mixer.session.beginConfiguration()
        layer.session = stream.mixer.session
        orientation = stream.mixer.videoIO.orientation
        stream.mixer.session.commitConfiguration()

        stream.lockQueue.async {
            stream.mixer.videoIO.renderer = self
            self.currentStream = stream
            stream.mixer.startRunning()
        }
    }
```

And if we replace it by this it works well:

```
open func attachStream(_ stream: NetStream?) {
        guard let stream: NetStream = stream else {
            layer.session?.stopRunning()
            layer.session = nil
            currentStream = nil
            return
        }

        stream.lockQueue.async { // <- The following lines are now inside the async block 
            stream.mixer.session.beginConfiguration()
            self.layer.session = stream.mixer.session
            self.orientation = stream.mixer.videoIO.orientation
            stream.mixer.session.commitConfiguration()

            stream.mixer.videoIO.renderer = self
            self.currentStream = stream
            stream.mixer.startRunning()
        }
    }
```

should I create a MR for this?

**Comment by usadmania** [comment] 2022-10-20 10:16
We are facing same issue in our app. Camera is either blank or still at same frame. Also, connection keep establishing and disconnecting again and again, network is stable though.

**Comment by mkrn** [comment] 2023-04-24 11:24
FYI I had black screen on some devices that did not support this setting:
rtmpStream.sessionPreset = AVCaptureSession.Preset.hd4K3840x2160
