### ISSUE TITLE
Airpods don't work when connected after example app launch.

### ISSUE THREAD

**Issue by mikolajadamowicz** [shogo4405/HaishinKit.swift#826] opened 2021-02-10 14:27 UTC
**Describe the bug**
I'm using an example app on the iPhone 6s with Airpods. Everything works fine but the minute AirPods got connected audio transforms into strange glitch like sounds. The thing is air pods work because these glitches are present exactly when I speak, they just don't encode correctly. I've tried changing sampleRate, audio bitrate, and AVAudioSession mode but nothing worked.  

**To Reproduce**
1. Run example app
2. Connect AirPods
3. Start streaming

**Expected behavior**
I should hear my voice

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: iOS 14.3

**Comment by kamingli** [comment] 2021-05-20 22:54
Hi @shogo4405, Do you have more information on this issue?  We would like to get this to work. :)

**Comment by msimonetta1** [comment] 2021-10-01 16:54
Hello @shogo4405 - I am also experiencing this issue. Wondering if you are able to provide any update on it. Thanks in advance.

**Comment by shogo4405** [comment] 2021-10-18 15:23
I can't reproduce it.
- Device: iPhone7Plus / iPhone 12 Pro max
- OS: iOS 14.8 / 15.0
- HaishinKit: 1.2.1

I will close this issue.

**Closed by shogo4405** 2021-10-18 15:23 UTC
