### ISSUE TITLE
MTHKView with many VideoEffects - preview is lagging

### ISSUE THREAD

**Issue by AdamAexol** [shogo4405/HaishinKit.swift#1350] opened 2023-12-08 15:45 UTC
### Describe the bug

MTHKView with a couple of VideoEffects camera preview is lagging.

### To Reproduce

I have MTHKView with camera preview and a couple of VideoEffects as camera overlays. Camera preview on MTHKView is lagging like this: https://youtu.be/nODP8NVQmN8

I identified that this commit is causing it:
https://github.com/shogo4405/HaishinKit.swift/commit/d9ce7421598f5055bb4acbdf09796643bc326da1

### Expected behavior

On the forked repository, I tried to fix it. 

In file IOVideoUnit.swift with those lines:
```
var context: CIContext {
        get {
            return lockQueue.sync { self.videoMixer.context }
        }
        set {
            lockQueue.async {
                self.videoMixer.context = newValue
            }
        }
    }
```
changed to this (lockQueue removed):
```
var context: CIContext {
        get {
            self.videoMixer.context
        }
        set {
            self.videoMixer.context = newValue
        }
    }
```
camera preview started working fine https://youtu.be/65SxuXcXhyk
but on the other hand, sometimes there is a problem connecting to live stream. I guess calling those lines of code on lockQueue had a purpose.

The interesting thing is that it doesn't occur on every device.
On iPhone 7 Plus iOS 15.8, iPhone 12 iOS 17 camera preview is lagging
On iPhone 14 Pro iOS 17 everything is working smoothly

Do you have any ideas on how to fix this issue?

### Version

1.7.1

### Smartphone info.

iPhone 7 Plus iOS 15.8, iPhone 12 iOS 17 - those devices are affected
iPhone 14 Pro iOS 17 - works fine

**Comment by shogo4405** [comment] 2023-12-09 04:21
The issue could not be reproduced with the combination of the example app and iPhone 7 Plus. I would like to have sample code demonstrating how you are using the library.

**Comment by shogo4405** [comment] 2023-12-09 04:30
Is the improvement not addressed in this commit?. a5c0b3a8

**Comment by shogo4405** [comment] 2023-12-13 12:44
Regarding the connection issue, I'm not quite sure because it works on my end. I would like you to review if there are any issues with the network or other related aspects.

**Comment by shogo4405** [comment] 2023-12-13 12:45
This issue itself has been completed, so I will close it.

**Closed by shogo4405** 2023-12-13 12:45 UTC
