### ISSUE TITLE
Camera Preview and UX freezes while recording starts

### ISSUE THREAD

**Issue by mkrn** [shogo4405/HaishinKit.swift#1574] opened 2024-09-19 14:32 UTC
### Describe the bug

In my app there's visible camera jerkiness after 

```
self.recorder.startRunning()

self.rtmpConnection.connect(self.uri)
```
 
It doesn't make a difference if I do it async with Task, or in background thread 

I'm using 

```
struct MTHKSwiftUiView: UIViewRepresentable {
    var mthkView = MTHKView(frame: .zero)

    @Binding var rtmpStream: RTMPStream
    var videoGravity: AVLayerVideoGravity

    init(rtmpStream: Binding<RTMPStream>, videoGravity: AVLayerVideoGravity = .resizeAspectFill) {
        self._rtmpStream = rtmpStream
        self.videoGravity = videoGravity
    }

    func makeUIView(context: Context) -> MTHKView {
        mthkView.videoGravity = videoGravity
        mthkView.videoOrientation = .landscapeRight
        return mthkView
    }

    func updateUIView(_ uiView: MTHKView, context: Context) {
        mthkView.attachStream(rtmpStream)
    }
}

```

### To Reproduce

Connect to stream 
Watch video hang and lag... 

### Expected behavior

Smooth video preview while it's connecting

### Version

1.9.4

### Smartphone info.

- iPhone 13 Pro
- iOS 18

**Comment by shogo4405** [comment] 2024-09-20 16:35
Hmm. I don’t think it froze the first time I made it… Maybe it’s due to an OS update.

It seems to be happening here:

https://github.com/shogo4405/HaishinKit.swift/blob/2c7c328b97754fc3d5310cdcfc85a3310158ea8a/Sources/IO/IOStreamRecorder.swift#L97-L98
I’ll try the solution I found in this related issue: https://github.com/flutter/flutter/issues/151319

**Comment by shogo4405** [comment] 2024-09-27 11:05
I tried flutter/flutter#151319, but it didn’t work, and it seemed to be a different issue. After retesting, it looked like the trigger was launching from Xcode.

## A. Reproducible:
1. Launch the Example iOS app on iPhone from Xcode.
1. Execute Recorder.startRecording().

## B. Not Reproducible:
1. Stop Xcode.
1. Launch the Example iOS app from the app list on iOS.
1. Execute Recorder.startRecording().

If it is not reproducible with the B steps, I would like to close the issue as it does not affect end users and is difficult to resolve. I would appreciate it if you could confirm that it does not occur with the B steps.

**Comment by mkrn** [comment] 2024-09-27 13:27
You are right! This is Xcode related. Safe to close now

**Closed** 2024-09-27 14:33 UTC
Labels: bug
