### ISSUE TITLE
SocketStream write error when network is changed.

### ISSUE THREAD

**Issue by wolfcon** [shogo4405/HaishinKit.swift#685] opened 2020-05-12 03:03 UTC
Sometimes may cause app crash. Not always.

### Error Description
`SocketStream write error [0x0]: 1 57`
![image](https://user-images.githubusercontent.com/1538729/81633717-f3103e80-943f-11ea-8e22-fab40938a22b.png)

### Exception code line
NetSocket.swift

Line: `102`
![image](https://user-images.githubusercontent.com/1538729/81633692-e7247c80-943f-11ea-81f8-f1647f59e697.png)

### Additional context
Kit version: `1.0.8`

### Ref 
#611 
#654

**Comment by mkrn** [comment] 2020-05-12 09:45
Hi @wolfcon, thanks for reporting! It's a duplicate of #606 Happens occasionally when network is bad

**Comment by wolfcon** [comment] 2020-05-12 10:13
thx. srr for duplication

**Closed** 2020-05-13 07:19 UTC
